### ISSUE TITLE
Cannot compile on MX Linux 23.2

### ISSUE THREAD

**Issue by needslithium** [brummer10/XTinyTerror.lv2#5]
I opened an issue report for the Dark Terror plugin with the same problem. Unfortunately both plugins have the same exact issue, reporting error code 1 for a missing include file "lv2.h" and then an undisclosed error code 2 immediately following.

`plugin/XDarkTerror.h:25:10: fatal error: lv2.h: No such file or directory
   25 | #include <lv2.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:150: XDarkTerror] Error 1
make[1]: Leaving directory '/home/___/git/XDarkTerror.lv2/XDarkTerror'
make: *** [Makefile:32: XDarkTerror] Error 2
`

**Comment by brummer10** [comment]
There was a unconventional switch in the lv2 include path which leads to this situation. It should be fixed with the last commit now.
